# Generated by Django 2.2.13 on 2020-08-17 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0006_auto_20200811_1551"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ("-pub_date",)},
        ),
    ]
